services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./.env:/app/.env
    env_file: .env
    # environment:
    #   SERVER_ENV: ${SERVER_ENV}
    environment:
      - SERVER_ENV=${SERVER_ENV}
      - POSTGRES_HOST=db
      - API_BASE_URL=
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
  simulation:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    env_file: .env
    environment:
      - POSTGRES_HOST=db
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - rides-db:/var/lib/postgresql/data
    env_file: .env
    command:
      - "-c"
      - "shared_buffers=64MB"
      - "-c"
      - "effective_cache-size=64MB"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

volumes:
  rides-db:
    external: true
